/**
 * Copyright 2014 deib-polimi
 * Contact: deib-polimi <marco.miglierina@polimi.it>
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 03:54:13 PM CET 
//


package it.polimi.modaclouds.qos_models;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for constraint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="constraint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="targetResourceIDRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="metric" type="{http://www.modaclouds.eu/xsd/1.0/metrics_schema}metricString"/>
 *         &lt;element name="metricAggregation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="parameter" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="aggregateFunction" type="{http://www.modaclouds.eu/xsd/1.0/aggregate_functions_schema}aggFunString" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="range">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="hasMaxValue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="hasMinValue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="inSet" type="{http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema}set" minOccurs="0"/>
 *                   &lt;element name="outSet" type="{http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema}set" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "constraint", namespace = "http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema", propOrder = {
    "targetResourceIDRef",
    "metric",
    "metricAggregation",
    "range",
    "priority"
})
public class Constraint {

    @XmlElement(required = true)
    protected String targetResourceIDRef;
    @XmlElement(required = true)
    protected String metric;
    protected Constraint.MetricAggregation metricAggregation;
    @XmlElement(required = true)
    protected Constraint.Range range;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger priority;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the targetResourceIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetResourceIDRef() {
        return targetResourceIDRef;
    }

    /**
     * Sets the value of the targetResourceIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetResourceIDRef(String value) {
        this.targetResourceIDRef = value;
    }

    /**
     * Gets the value of the metric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetric() {
        return metric;
    }

    /**
     * Sets the value of the metric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetric(String value) {
        this.metric = value;
    }

    /**
     * Gets the value of the metricAggregation property.
     * 
     * @return
     *     possible object is
     *     {@link Constraint.MetricAggregation }
     *     
     */
    public Constraint.MetricAggregation getMetricAggregation() {
        return metricAggregation;
    }

    /**
     * Sets the value of the metricAggregation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Constraint.MetricAggregation }
     *     
     */
    public void setMetricAggregation(Constraint.MetricAggregation value) {
        this.metricAggregation = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link Constraint.Range }
     *     
     */
    public Constraint.Range getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link Constraint.Range }
     *     
     */
    public void setRange(Constraint.Range value) {
        this.range = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority(BigInteger value) {
        this.priority = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="parameter" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="aggregateFunction" type="{http://www.modaclouds.eu/xsd/1.0/aggregate_functions_schema}aggFunString" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameter"
    })
    public static class MetricAggregation {

        @XmlElement(namespace = "http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema")
        @XmlSchemaType(name = "anySimpleType")
        protected List<Object> parameter;
        @XmlAttribute(name = "aggregateFunction")
        protected String aggregateFunction;

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getParameter() {
            if (parameter == null) {
                parameter = new ArrayList<Object>();
            }
            return this.parameter;
        }

        /**
         * Gets the value of the aggregateFunction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAggregateFunction() {
            return aggregateFunction;
        }

        /**
         * Sets the value of the aggregateFunction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAggregateFunction(String value) {
            this.aggregateFunction = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="hasMaxValue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="hasMinValue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="inSet" type="{http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema}set" minOccurs="0"/>
     *         &lt;element name="outSet" type="{http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema}set" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hasMaxValue",
        "hasMinValue",
        "inSet",
        "outSet"
    })
    public static class Range {

        @XmlElement(namespace = "http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema")
        protected Float hasMaxValue;
        @XmlElement(namespace = "http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema")
        protected Float hasMinValue;
        @XmlElement(namespace = "http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema")
        protected Set inSet;
        @XmlElement(namespace = "http://www.modaclouds.eu/xsd/1.0/qos_constraints_schema")
        protected Set outSet;

        /**
         * Gets the value of the hasMaxValue property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getHasMaxValue() {
            return hasMaxValue;
        }

        /**
         * Sets the value of the hasMaxValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setHasMaxValue(Float value) {
            this.hasMaxValue = value;
        }

        /**
         * Gets the value of the hasMinValue property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getHasMinValue() {
            return hasMinValue;
        }

        /**
         * Sets the value of the hasMinValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setHasMinValue(Float value) {
            this.hasMinValue = value;
        }

        /**
         * Gets the value of the inSet property.
         * 
         * @return
         *     possible object is
         *     {@link Set }
         *     
         */
        public Set getInSet() {
            return inSet;
        }

        /**
         * Sets the value of the inSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link Set }
         *     
         */
        public void setInSet(Set value) {
            this.inSet = value;
        }

        /**
         * Gets the value of the outSet property.
         * 
         * @return
         *     possible object is
         *     {@link Set }
         *     
         */
        public Set getOutSet() {
            return outSet;
        }

        /**
         * Sets the value of the outSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link Set }
         *     
         */
        public void setOutSet(Set value) {
            this.outSet = value;
        }

    }

}
