/**
 * Copyright 2014 deib-polimi
 * Contact: deib-polimi <marco.miglierina@polimi.it>
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 03:54:13 PM CET 
//


package it.polimi.modaclouds.qos_models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for monitoringRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="monitoringRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="monitoredTargets" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="monitoredTarget" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="useParentTargets" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="metricAggregation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="parameter" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="useParentFields" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="groupingCategory" type="{http://www.modaclouds.eu/xsd/1.0/grouping_categories_schema}groupCatString" />
 *                 &lt;attribute name="aggregateFunction" type="{http://www.modaclouds.eu/xsd/1.0/aggregate_functions_schema}aggFunString" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="actions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="action" type="{http://www.modaclouds.eu/xsd/1.0/actions_schema}action" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="useParentActions" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relatedQosConstraintId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentMonitoringRuleId" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="metricName" type="{http://www.modaclouds.eu/xsd/1.0/metrics_schema}metricString" />
 *       &lt;attribute name="timeStep" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="timeWindow" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="startEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="samplingTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="samplingProbability" type="{http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema}probability" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "monitoringRule", namespace = "http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema", propOrder = {
    "monitoredTargets",
    "metricAggregation",
    "condition",
    "actions"
})
public class MonitoringRule {

    protected MonitoringRule.MonitoredTargets monitoredTargets;
    protected MonitoringRule.MetricAggregation metricAggregation;
    protected String condition;
    protected MonitoringRule.Actions actions;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "label", required = true)
    protected String label;
    @XmlAttribute(name = "relatedQosConstraintId")
    protected String relatedQosConstraintId;
    @XmlAttribute(name = "parentMonitoringRuleId")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object parentMonitoringRuleId;
    @XmlAttribute(name = "metricName")
    protected String metricName;
    @XmlAttribute(name = "timeStep")
    protected Integer timeStep;
    @XmlAttribute(name = "timeWindow")
    protected Integer timeWindow;
    @XmlAttribute(name = "startEnabled")
    protected Boolean startEnabled;
    @XmlAttribute(name = "samplingTime")
    protected Integer samplingTime;
    @XmlAttribute(name = "samplingProbability")
    protected Float samplingProbability;

    /**
     * Gets the value of the monitoredTargets property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringRule.MonitoredTargets }
     *     
     */
    public MonitoringRule.MonitoredTargets getMonitoredTargets() {
        return monitoredTargets;
    }

    /**
     * Sets the value of the monitoredTargets property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringRule.MonitoredTargets }
     *     
     */
    public void setMonitoredTargets(MonitoringRule.MonitoredTargets value) {
        this.monitoredTargets = value;
    }

    /**
     * Gets the value of the metricAggregation property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringRule.MetricAggregation }
     *     
     */
    public MonitoringRule.MetricAggregation getMetricAggregation() {
        return metricAggregation;
    }

    /**
     * Sets the value of the metricAggregation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringRule.MetricAggregation }
     *     
     */
    public void setMetricAggregation(MonitoringRule.MetricAggregation value) {
        this.metricAggregation = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringRule.Actions }
     *     
     */
    public MonitoringRule.Actions getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringRule.Actions }
     *     
     */
    public void setActions(MonitoringRule.Actions value) {
        this.actions = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the relatedQosConstraintId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedQosConstraintId() {
        return relatedQosConstraintId;
    }

    /**
     * Sets the value of the relatedQosConstraintId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedQosConstraintId(String value) {
        this.relatedQosConstraintId = value;
    }

    /**
     * Gets the value of the parentMonitoringRuleId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getParentMonitoringRuleId() {
        return parentMonitoringRuleId;
    }

    /**
     * Sets the value of the parentMonitoringRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setParentMonitoringRuleId(Object value) {
        this.parentMonitoringRuleId = value;
    }

    /**
     * Gets the value of the metricName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetricName() {
        return metricName;
    }

    /**
     * Sets the value of the metricName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetricName(String value) {
        this.metricName = value;
    }

    /**
     * Gets the value of the timeStep property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimeStep() {
        return timeStep;
    }

    /**
     * Sets the value of the timeStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeStep(Integer value) {
        this.timeStep = value;
    }

    /**
     * Gets the value of the timeWindow property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimeWindow() {
        return timeWindow;
    }

    /**
     * Sets the value of the timeWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeWindow(Integer value) {
        this.timeWindow = value;
    }

    /**
     * Gets the value of the startEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStartEnabled() {
        return startEnabled;
    }

    /**
     * Sets the value of the startEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStartEnabled(Boolean value) {
        this.startEnabled = value;
    }

    /**
     * Gets the value of the samplingTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSamplingTime() {
        return samplingTime;
    }

    /**
     * Sets the value of the samplingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSamplingTime(Integer value) {
        this.samplingTime = value;
    }

    /**
     * Gets the value of the samplingProbability property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSamplingProbability() {
        return samplingProbability;
    }

    /**
     * Sets the value of the samplingProbability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSamplingProbability(Float value) {
        this.samplingProbability = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="action" type="{http://www.modaclouds.eu/xsd/1.0/actions_schema}action" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="useParentActions" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "action"
    })
    public static class Actions {

        @XmlElement(namespace = "http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema")
        protected List<Action> action;
        @XmlAttribute(name = "useParentActions")
        protected Boolean useParentActions;

        /**
         * Gets the value of the action property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the action property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Action }
         * 
         * 
         */
        public List<Action> getAction() {
            if (action == null) {
                action = new ArrayList<Action>();
            }
            return this.action;
        }

        /**
         * Gets the value of the useParentActions property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isUseParentActions() {
            if (useParentActions == null) {
                return false;
            } else {
                return useParentActions;
            }
        }

        /**
         * Sets the value of the useParentActions property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUseParentActions(Boolean value) {
            this.useParentActions = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="parameter" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="useParentFields" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="groupingCategory" type="{http://www.modaclouds.eu/xsd/1.0/grouping_categories_schema}groupCatString" />
     *       &lt;attribute name="aggregateFunction" type="{http://www.modaclouds.eu/xsd/1.0/aggregate_functions_schema}aggFunString" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameter"
    })
    public static class MetricAggregation {

        @XmlElement(namespace = "http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema")
        @XmlSchemaType(name = "anySimpleType")
        protected List<Object> parameter;
        @XmlAttribute(name = "useParentFields")
        protected Boolean useParentFields;
        @XmlAttribute(name = "groupingCategory")
        protected String groupingCategory;
        @XmlAttribute(name = "aggregateFunction")
        protected String aggregateFunction;

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getParameter() {
            if (parameter == null) {
                parameter = new ArrayList<Object>();
            }
            return this.parameter;
        }

        /**
         * Gets the value of the useParentFields property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isUseParentFields() {
            if (useParentFields == null) {
                return false;
            } else {
                return useParentFields;
            }
        }

        /**
         * Sets the value of the useParentFields property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUseParentFields(Boolean value) {
            this.useParentFields = value;
        }

        /**
         * Gets the value of the groupingCategory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroupingCategory() {
            return groupingCategory;
        }

        /**
         * Sets the value of the groupingCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroupingCategory(String value) {
            this.groupingCategory = value;
        }

        /**
         * Gets the value of the aggregateFunction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAggregateFunction() {
            return aggregateFunction;
        }

        /**
         * Sets the value of the aggregateFunction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAggregateFunction(String value) {
            this.aggregateFunction = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="monitoredTarget" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="useParentTargets" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "monitoredTarget"
    })
    public static class MonitoredTargets {

        @XmlElement(namespace = "http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema")
        protected List<MonitoringRule.MonitoredTargets.MonitoredTarget> monitoredTarget;
        @XmlAttribute(name = "useParentTargets")
        protected Boolean useParentTargets;

        /**
         * Gets the value of the monitoredTarget property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the monitoredTarget property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMonitoredTarget().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MonitoringRule.MonitoredTargets.MonitoredTarget }
         * 
         * 
         */
        public List<MonitoringRule.MonitoredTargets.MonitoredTarget> getMonitoredTarget() {
            if (monitoredTarget == null) {
                monitoredTarget = new ArrayList<MonitoringRule.MonitoredTargets.MonitoredTarget>();
            }
            return this.monitoredTarget;
        }

        /**
         * Gets the value of the useParentTargets property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isUseParentTargets() {
            if (useParentTargets == null) {
                return false;
            } else {
                return useParentTargets;
            }
        }

        /**
         * Sets the value of the useParentTargets property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUseParentTargets(Boolean value) {
            this.useParentTargets = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class MonitoredTarget {

            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
