//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 11:26:42 AM CET 
//


package it.polimi.modaclouds.qos_models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for monitoringRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="monitoringRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="monitoredTargets" type="{http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema}monitoredTargets" minOccurs="0"/>
 *         &lt;element name="metricAggregation" type="{http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema}monitoringMetricAggregation" minOccurs="0"/>
 *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="actions" type="{http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema}actions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relatedQosConstraintId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentMonitoringRuleId" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="metricName" type="{http://www.modaclouds.eu/xsd/1.0/metrics_schema}metricString" />
 *       &lt;attribute name="timeStep" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="timeWindow" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="startEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="samplingTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="samplingProbability" type="{http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema}probability" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "monitoringRule", propOrder = {
    "monitoredTargets",
    "metricAggregation",
    "condition",
    "actions"
})
public class MonitoringRule {

    protected MonitoredTargets monitoredTargets;
    protected MonitoringMetricAggregation metricAggregation;
    protected String condition;
    protected Actions actions;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "label", required = true)
    protected String label;
    @XmlAttribute(name = "relatedQosConstraintId")
    protected String relatedQosConstraintId;
    @XmlAttribute(name = "parentMonitoringRuleId")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object parentMonitoringRuleId;
    @XmlAttribute(name = "metricName")
    protected String metricName;
    @XmlAttribute(name = "timeStep")
    protected Integer timeStep;
    @XmlAttribute(name = "timeWindow")
    protected Integer timeWindow;
    @XmlAttribute(name = "startEnabled")
    protected Boolean startEnabled;
    @XmlAttribute(name = "samplingTime")
    protected Integer samplingTime;
    @XmlAttribute(name = "samplingProbability")
    protected Float samplingProbability;

    /**
     * Gets the value of the monitoredTargets property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoredTargets }
     *     
     */
    public MonitoredTargets getMonitoredTargets() {
        return monitoredTargets;
    }

    /**
     * Sets the value of the monitoredTargets property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoredTargets }
     *     
     */
    public void setMonitoredTargets(MonitoredTargets value) {
        this.monitoredTargets = value;
    }

    /**
     * Gets the value of the metricAggregation property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringMetricAggregation }
     *     
     */
    public MonitoringMetricAggregation getMetricAggregation() {
        return metricAggregation;
    }

    /**
     * Sets the value of the metricAggregation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringMetricAggregation }
     *     
     */
    public void setMetricAggregation(MonitoringMetricAggregation value) {
        this.metricAggregation = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link Actions }
     *     
     */
    public Actions getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actions }
     *     
     */
    public void setActions(Actions value) {
        this.actions = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the relatedQosConstraintId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedQosConstraintId() {
        return relatedQosConstraintId;
    }

    /**
     * Sets the value of the relatedQosConstraintId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedQosConstraintId(String value) {
        this.relatedQosConstraintId = value;
    }

    /**
     * Gets the value of the parentMonitoringRuleId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getParentMonitoringRuleId() {
        return parentMonitoringRuleId;
    }

    /**
     * Sets the value of the parentMonitoringRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setParentMonitoringRuleId(Object value) {
        this.parentMonitoringRuleId = value;
    }

    /**
     * Gets the value of the metricName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetricName() {
        return metricName;
    }

    /**
     * Sets the value of the metricName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetricName(String value) {
        this.metricName = value;
    }

    /**
     * Gets the value of the timeStep property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimeStep() {
        return timeStep;
    }

    /**
     * Sets the value of the timeStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeStep(Integer value) {
        this.timeStep = value;
    }

    /**
     * Gets the value of the timeWindow property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimeWindow() {
        return timeWindow;
    }

    /**
     * Sets the value of the timeWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeWindow(Integer value) {
        this.timeWindow = value;
    }

    /**
     * Gets the value of the startEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStartEnabled() {
        return startEnabled;
    }

    /**
     * Sets the value of the startEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStartEnabled(Boolean value) {
        this.startEnabled = value;
    }

    /**
     * Gets the value of the samplingTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSamplingTime() {
        return samplingTime;
    }

    /**
     * Sets the value of the samplingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSamplingTime(Integer value) {
        this.samplingTime = value;
    }

    /**
     * Gets the value of the samplingProbability property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSamplingProbability() {
        return samplingProbability;
    }

    /**
     * Sets the value of the samplingProbability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSamplingProbability(Float value) {
        this.samplingProbability = value;
    }

}
