/**
 * Copyright 2014 deib-polimi
 * Contact: deib-polimi <marco.miglierina@polimi.it>
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.04 at 03:54:13 PM CET 
//


package it.polimi.modaclouds.qos_models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polimi.modaclouds.qos_models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polimi.modaclouds.qos_models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Constraint }
     * 
     */
    public Constraint createConstraint() {
        return new Constraint();
    }

    /**
     * Create an instance of {@link MonitoringRule }
     * 
     */
    public MonitoringRule createMonitoringRule() {
        return new MonitoringRule();
    }

    /**
     * Create an instance of {@link MonitoringRule.MonitoredTargets }
     * 
     */
    public MonitoringRule.MonitoredTargets createMonitoringRuleMonitoredTargets() {
        return new MonitoringRule.MonitoredTargets();
    }

    /**
     * Create an instance of {@link AggregateFunctions }
     * 
     */
    public AggregateFunctions createAggregateFunctions() {
        return new AggregateFunctions();
    }

    /**
     * Create an instance of {@link AggregateFunction }
     * 
     */
    public AggregateFunction createAggregateFunction() {
        return new AggregateFunction();
    }

    /**
     * Create an instance of {@link Metrics }
     * 
     */
    public Metrics createMetrics() {
        return new Metrics();
    }

    /**
     * Create an instance of {@link it.polimi.modaclouds.qos_models.Actions }
     * 
     */
    public it.polimi.modaclouds.qos_models.Actions createActions() {
        return new it.polimi.modaclouds.qos_models.Actions();
    }

    /**
     * Create an instance of {@link ActionDescription }
     * 
     */
    public ActionDescription createActionDescription() {
        return new ActionDescription();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link GroupingCategories }
     * 
     */
    public GroupingCategories createGroupingCategories() {
        return new GroupingCategories();
    }

    /**
     * Create an instance of {@link MonitoringRules }
     * 
     */
    public MonitoringRules createMonitoringRules() {
        return new MonitoringRules();
    }

    /**
     * Create an instance of {@link Constraints }
     * 
     */
    public Constraints createConstraints() {
        return new Constraints();
    }

    /**
     * Create an instance of {@link Set }
     * 
     */
    public Set createSet() {
        return new Set();
    }

    /**
     * Create an instance of {@link Constraint.MetricAggregation }
     * 
     */
    public Constraint.MetricAggregation createConstraintMetricAggregation() {
        return new Constraint.MetricAggregation();
    }

    /**
     * Create an instance of {@link Constraint.Range }
     * 
     */
    public Constraint.Range createConstraintRange() {
        return new Constraint.Range();
    }

    /**
     * Create an instance of {@link MonitoringRule.MetricAggregation }
     * 
     */
    public MonitoringRule.MetricAggregation createMonitoringRuleMetricAggregation() {
        return new MonitoringRule.MetricAggregation();
    }

    /**
     * Create an instance of {@link MonitoringRule.Actions }
     * 
     */
    public MonitoringRule.Actions createMonitoringRuleActions() {
        return new MonitoringRule.Actions();
    }

    /**
     * Create an instance of {@link MonitoringRule.MonitoredTargets.MonitoredTarget }
     * 
     */
    public MonitoringRule.MonitoredTargets.MonitoredTarget createMonitoringRuleMonitoredTargetsMonitoredTarget() {
        return new MonitoringRule.MonitoredTargets.MonitoredTarget();
    }

}
