//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 11:26:42 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.polimi.modaclouds.qos_models;
